name: release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  godoc:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - name: Wait 1 minute
        # make sure that new the tag is available for pkg.go.dev
        run: sleep 60
      - name: Update pkg.go.dev
        run: curl https://proxy.golang.org/github.com/${{ github.repository }}/v2/@v/${{ github.ref_name }}.info
